language: ruby
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
gemfile:
  - gemfiles/activemodel_4_2.gemfile
  - gemfiles/activemodel_5_0.gemfile
matrix:
  exclude:
    - gemfile: gemfiles/activemodel_5_0.gemfile
      rvm: 2.1.10
  allow_failures:
branches:
  only:
    - master
