# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "accept_values_for"
  s.version = "0.4.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bogdan Gusiev"]
  s.date = "2013-14-05"
  s.description = "Rspec: When you have a complex validation(e.g. regexp or custom method) on ActiveRecord model\nyou have to write annoying easy specs on which values should be accepted by your validation method and which should not.\naccepts_values_for rspec matcher simplify the code. See example for more information.\n"
  s.email = "agresso@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    ".travis.yml",
    "Changelog.textile",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "Rakefile",
    "Readme.md",
    "VERSION",
    "accept_values_for.gemspec",
    "lib/accept_values_for.rb",
    "lib/discover.rb",
    "spec/accept_values_for_spec.rb",
    "spec/discover_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/bogdan/accept_values_for"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "In order to test a complex validation for ActiveRecord models Implemented accept_values_for custom rspec matcher"
  s.test_files = [
    "spec/accept_values_for_spec.rb",
    "spec/discover_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      s.add_runtime_dependency(%q<activemodel>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<activerecord>, [">= 3.0.0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 2.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
    else
      s.add_dependency(%q<activemodel>, [">= 3.0.0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 3.0.0"])
      s.add_dependency(%q<rspec-rails>, [">= 2.0.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    end
  else
    s.add_dependency(%q<activemodel>, [">= 3.0.0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 3.0.0"])
    s.add_dependency(%q<rspec-rails>, [">= 2.0.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
  end
end

